# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [failarmy, ss82]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username hunters.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username opera
issuehunt: # Replace with a single IssueHunt username knight line
otechie: # Replace with a single Otechie username Wikipedia87
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://marlboro.com','https://current.com','https://ultra.com','https://911truth.org','https://mad.org','https://iheartmob.org','https://chime.com']
